# Adapted from https://github.com/marketplace/actions/remove-artifacts (available under MIT license)

name: Remove Old Artifacts

on:
  schedule:
    # Every 15 minutes
    - cron: '0 1 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove Old Artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minutes'